name: Build and Deploy Worker

on:
  push:
    branches:
      - luxiangchuan-patch-1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Enable Debug Logs
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build project
        run: |
          echo "Building the project..."
          npx wrangler deploy src/worker.js --name bpb-worker-panel --compatibility-flag [nodejs_compat] --compatibility-date 2024-10-26 --dry-run --outdir=dist

      - name: Copy built file
        run: |
          echo "Copying built file..."
          cp dist/worker.js _worker.js

      - name: Check copied file
        run: |
          echo "Verifying copied file..."
          ls -la _worker.js

      - name: Commit and push built worker to root
        run: |
          echo "Configuring git..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo "Adding changes to git..."
          git add _worker.js
          echo "Committing changes..."
          git commit -m "Automated build: update _worker.js" || echo "No changes to commit"
          echo "Pushing changes..."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
